subshell exit trap test

diff --git a/wal-telegram b/wal-telegram
--- a/wal-telegram
+++ b/wal-telegram
@@ -8,6 +8,10 @@
 # Make it so the option order doesn't matter
 
 # Help function called by the --help|-h parameter.
+
+set -E
+trap '[ "$?" -ne 77 ] || exit 77' ERR
+
 help() {
   cat <<EOF
 Use the --wal (or -w) parameter if you want to generate a Telegram palette that uses the colors generated by pywal/wal.
@@ -28,17 +32,17 @@ EOF
 script_dir=$(readlink -f ${0} | sed "s#/$(basename ${0})##")
 
 # shellcheck source=/dev/null
-command -v zip > /dev/null || (echo "A zipping utility is needed for this script, consider installing zip or gzip" && exit 0)
+command -v zip > /dev/null || (echo "A zipping utility is needed for this script, consider installing zip or gzip" && exit 77)
 [[ "$1" == --help || "$1" == -h || -z "$1" ]] && help && exit 0
 [[ "$2" && "$1" == --palette || "$1" == -p ]] && mode="palette" && . "$2"
 [[ "$1" == --wal  || "$1" == -w ]] && mode="wal"
 if [[ "$mode" == wal ]]; then
-  [ ! -d "${HOME}/.cache/wal" ] && echo "wal must be run before running wal-telegram." && exit 0
+  [ ! -d "${HOME}/.cache/wal" ] && echo "wal must be run before running wal-telegram." && exit 77
   . "${HOME}/.cache/wal/colors.sh"
 fi
 bg="background"
 [[ "$2" && "$mode" == wal && ("$2" == --tiled || "$2" == -t) ]] && bg="tiled"
-[[ "$mode" == palette && -f "$2" ]] || (echo "Palette error." && help && exit 0)
+[[ "$mode" == palette && ! -f "$2" ]] && echo "Palette error." && help && exit 77
 [[ "$3" && "$mode" == palette && ("$3" == --tiled || "$3" == -t) ]] && bg="tiled"
 
 # Prepare the conditions for the other functions.
@@ -305,10 +309,7 @@ EOF
 }
 
 main() {
-  prepare
-  create_colors
-  create_palette
-  printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mPalette generated succesfully.\\e[0m"
+  prepare && create_colors && create_palette printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mPalette generated succesfully.\\e[0m"
 }
 
 main
