options now using getopt / new -b option to specify a background image / fixed -p not finding the wal background correctly

diff --git a/wal-telegram b/wal-telegram
--- a/wal-telegram
+++ b/wal-telegram
@@ -4,9 +4,6 @@
 # or from a different file containing the hex colors (see the README.md for the
 # format of the file).
 
-# TODO
-# Make it so the option order doesn't matter
-
 # Help function called by the --help|-h parameter.
 
 set -E
@@ -14,34 +11,99 @@ trap '[ "$?" -ne 77 ] || exit 77' ERR
 
 help() {
   cat <<EOF
-Use the --wal (or -w) parameter if you want to generate a Telegram palette that uses the colors generated by pywal/wal.
-Use the --palette (or -p) '/path/to/palette' parameter if you want to generate a Telegram palette that uses the colors from a colorscheme specified in a text file.
-Use the --tiled (or -t) option to use a unified color tiling backgroung.
-Use the --help (or -h) to call this help function.
+A script to create Telegram palettes that use colors generated by pywal/wal
+or from a different file containing the hex colors (see the README.md for the
+format of the file).
 
-/!\ Option order is important for now
+Usage: 
+  $0 -w | --wal [-t|--tiled] [-b|--background=<path_to_background_image>]
+  $0 -p | --palette=</path/to/palette> [-t|--tiled] [-b|--background=<path_to_background_image>]"
+  $0 -h | --help
 
-e.g.
-  wal-telegram --wal
-  wal-telegram --wal --tiled
-  wal-telegram --palette ~/progetti/themes/sh/material-default.sh
-  wal-telegram --palette ~/progetti/themes/sh/material-default.sh --tiled
+Options:
+  -h                Show command usage.
+  --help            Show this help screen.
+  -w --wal          Generate the color palette using the colors generated
+                    by pywal/wal (default).
+  -p --palette      Use colors from an sh file to generate the color palette.
+  -t --tiled        Use a unified color background instead of an image.
+  -b --background   Use a specific image as background.
 EOF
+}
+usage() {
+  cat <<EOF
+Usage:
+  $0 --wal [--tiled] [--background=<path_to_background_image>]
+  $0 --palette=<path_to_sh_file> [--tiled] [--background=<path_to_background_image>]
+EOF
+}
+exit_abnormal(){
+  usage
+  exit 1
 }
 
 script_dir=$(readlink -f ${0} | sed "s#/$(basename ${0})##")
 
 # shellcheck source=/dev/null
-command -v zip > /dev/null || (echo "A zipping utility is needed for this script, consider installing zip or gzip" && exit 77)
-[[ "$1" == --help || "$1" == -h || -z "$1" ]] && help && exit 0
-[[ "$1" == --palette || "$1" == -p ]] && mode="palette" && [[ ! -f "$2" ]] && echo "Palette error see --help for usage examples." && exit 77
-[[ "$mode" == palette ]] && . "$2"
-[[ "$1" == --wal  || "$1" == -w ]] && mode="wal" && [ ! -d "${HOME}/.cache/wal" ] && echo "wal must be run before running wal-telegram." && exit 77
-[[ "$mode" == wal ]] && . "${HOME}/.cache/wal/colors.sh"
-bg="background"
-[[ "$2" && "$mode" == wal && ("$2" == --tiled || "$2" == -t) ]] && bg="tiled"
-[[ "$3" && "$mode" == palette && ("$3" == --tiled || "$3" == -t) ]] && bg="tiled"
-[[ -z $mode ]] && help && exit 77
+command -v zip > /dev/null || (printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mA zipping utility is needed for this script, consider installing zip or gzip\\e[0m" && exit 77)
+
+options=$(getopt -o hwtp:b: --long help,wal,tiled,palette:,background: -- "$@")
+if [ $? != 0 ] ; then exit_abnormal; fi
+eval set -- "$options"
+
+while true; do
+  case "$1" in
+    -h) usage; exit 0 ;;
+    --help) help; exit 0 ;;
+    -w | --wal )
+      if [[ "$mode" == 'palette' ]]; then
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mCannot use wal and palette together.\\e[0m"
+        exit_abnormal
+      fi
+      if [[ ! -d "${HOME}/.cache/wal" ]]; then
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mWal must be run before running wal-telegram.\\e[0m"
+        exit_abnormal
+      fi
+      mode='wal'
+      shift ;;
+    -t | --tiled )
+      bg_mode="tiled"
+      shift ;;
+    -p | --palette )
+      if [[ "$mode" == 'wal' ]]; then
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mCannot use wal and palette together.\\e[0m"
+        exit_abnormal
+      fi
+      if [[ ! -f "$2" ]]; then
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mPalette file '$2' could not be found.\\e[0m"
+        exit_abnormal
+      fi
+      mode='palette'
+      shift 2 ;;
+    -b | --background )
+      if [[ ! -f "$2" ]]; then
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mBackground file '$2' could not be found.\\e[0m"
+        exit_abnormal
+      fi
+      bg="$2"
+      shift 2 ;;
+    -- ) shift; break ;;
+    * ) break ;;
+  esac
+done
+# default values
+[ -z "$mode" ] && mode='wal'
+[ -z "$bg_mode" ] && bg_mode='background'
+[ -z "$bg" ] && bg='wal'
+
+# source this here in case wal is not an option
+if [[ "$mode" == 'wal' ]]; then
+  . "${HOME}/.cache/wal/colors.sh"
+fi
+
+if [[ "$bg_mode" == 'tiled' ]] && [[ "$bg" != 'wal' ]]; then
+  printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mBackground option while using tiled mode is useless.\\e[0m"
+fi
 
 # Prepare the conditions for the other functions.
 prepare() {
@@ -54,22 +116,31 @@ prepare() {
   rm -f "${pre}/colors.tdesktop-theme"
   rm -f "${pre}/${mode}.tdesktop-theme"
 
-  if [[ "$mode" == wal ]]; then
-    wal_path="$(<"${HOME}/.cache/wal/wal")"
-    wal_ext="${wal_path##*.}"
-    cp "$wal_path" "${pre}/background.${wal_ext}"
-
-  elif [[ "$mode" == palette ]]; then
-    if [[ -f "${HOME}/.fehbg" ]]; then
-      wal_path="$(tail -n1 "${HOME}/.fehbg" \
-                 | awk '{print $3}' \
-                 | sed "s/'//g")"
-      wal_ext="${wal_path##*.}"
-      cp "$wal_path" "${pre}/background.${wal_ext}"
-    else
-      bg="tiled"
-    fi
-  fi
+  if [[ "$bg" == "wal" ]]; then # if no background is specified
+    if [[ "$mode" == wal ]] && [[ "$bg_mode" == "background" ]]; then
+      # wal mode without tiled
+      bg_path="$(<"${HOME}/.cache/wal/wal")"
+      bg_ext="${bg_path##*.}"
+      cp "$bg_path" "${pre}/background.${bg_ext}"
+    elif [[ "$mode" == "palette" ]] && [[ "$bg_mode" == "background" ]]; then
+      if [[ -f "${HOME}/.fehbg" ]]; then
+        bg_path="$(tail -n1 "${HOME}/.fehbg" \
+                   | sed "s/[^']*//" \
+                   | awk '{print $1}' \
+                   | sed "s/'//g")"
+        bg_ext="${bg_path##*.}"
+        if [[ -f "$bg_path" ]]; then
+          cp "$bg_path" "${pre}/background.${bg_ext}"
+        fi
+      else # if .fehbg exists
+        printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37m~/.fehbg not found, falling back to tiled background.\\e[0m"
+        bg="tiled"
+      fi # if .fehbg exists
+    fi # elif mode == palette
+  else # if bg == wal
+    bg_ext="${bg##*.}"
+    cp "$bg" "${pre}/background.${bg_ext}"
+  fi # if bg == wal
 }
 
 # Lighten/darken by 20%, 30%, 40%, 50%, 60% some colors using only pure bash.
@@ -301,8 +372,9 @@ EOF
   const="$(<"$script_dir/colors.wt-constants")"
   printf '%s' "$const" >> "${pre}/colors.tdesktop-theme"
   cd ${pre}
-  convert -size 256x256 "xc:$color0" tiled.${wal_ext}
-  zip -q ${mode}.tdesktop-theme colors.tdesktop-theme ${bg}.${wal_ext}
+  if [[ -z $bg_ext ]]; then bg_ext="png"; fi
+  convert -size 256x256 "xc:$color0" tiled.${bg_ext}
+  zip -q ${mode}.tdesktop-theme colors.tdesktop-theme ${bg_mode}.${bg_ext}
   rm -f ${pre}/colors.tdesktop-theme ${pre}/background.* ${pre}/tiled.*
 }
 
