mode was declared in subshell

diff --git a/wal-telegram b/wal-telegram
--- a/wal-telegram
+++ b/wal-telegram
@@ -29,14 +29,16 @@ script_dir=$(readlink -f ${0} | sed "s#/$(basename ${0})##")
 
 # shellcheck source=/dev/null
 command -v zip > /dev/null || (echo "A zipping utility is needed for this script, consider installing zip or gzip" && exit 0)
-[[ "$2" && "$1" == --palette || "$1" == -p ]] && mode="palette" && . "$2"
-if [[ "$1" == --wal  || "$1" == -w ]]; then
-  [ -d "${HOME}/.cache/wal" ] || echo "wal must be run before running wal-telegram." && exit 0
-  mode="wal" && . "${HOME}/.cache/wal/colors.sh"
-fi
 [[ "$1" == --help || "$1" == -h || -z "$1" ]] && help && exit 0
+[[ "$2" && "$1" == --palette || "$1" == -p ]] && mode="palette" && . "$2"
+[[ "$1" == --wal  || "$1" == -w ]] && mode="wal"
+if [[ "$mode" == wal ]]; then
+  [ ! -d "${HOME}/.cache/wal" ] && echo "wal must be run before running wal-telegram." && exit 0
+  . "${HOME}/.cache/wal/colors.sh"
+fi
 bg="background"
 [[ "$2" && "$mode" == wal && ("$2" == --tiled || "$2" == -t) ]] && bg="tiled"
+[[ "$mode" == palette && -f "$2" ]] || (echo "Palette error." && help && exit 0)
 [[ "$3" && "$mode" == palette && ("$3" == --tiled || "$3" == -t) ]] && bg="tiled"
 
 # Prepare the conditions for the other functions.
